# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'

pool: Default

stages:

- template: ./pipelines/build-terraform.yml
  parameters:
    env: prd
    app: helloworld