parameters:
- name : env
  type: string
- name: app
  type: string


stages:
  - stages: build_${{ parameters.env }}
    displayName: 'Terraform Build - ${{upper(parameters.app) upper(parameters.env) }}'
    condition: always()
    jobs:
    - job: Build
      displayName: 'Build - ${{upper(parameters.app) upper(parameters.env) }}'
      steps:
      - checkout: self
      - task: AzureKeyVault@2
        inputs
