parameters:
- name : env
  type: string
- name: app
  type: string


stages:
  - stage: build_${{ parameters.env }}
    displayName: 'Terraform Build - ${{upper(parameters.app) }} ${{ upper(parameters.env) }}'
    condition: always()
    jobs:
    - job: Build
      displayName: 'Build - ${{upper(parameters.app) }} ${{ upper(parameters.env) }}'
      steps:
      - checkout: self
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'ado_to_keyvault'
          KeyVaultName: 'MCM-TF-Keys'
          SecretsFilter: '*'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: sudo apt-get -y install zip
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Azure subscription 1(5fdbca41-d6cf-45c0-8ed0-e213025b7099)'
          backendAzureRmResourceGroupName: 'tfstate'
          backendAzureRmStorageAccountName: 'tfstate2n08y'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
